#Generated Form Function
function GenerateForm {
########################################################################
# Code Generated By: SAPIEN Technologies PrimalForms (Community Edition) v1.0.10.0
# Generated On: 2/18/2014 4:02 PM
# Generated By: smithsa
########################################################################

#region Import the Assemblies
[reflection.assembly]::loadwithpartialname("System.Windows.Forms") | Out-Null
[reflection.assembly]::loadwithpartialname("System.Drawing") | Out-Null
#endregion

#region Generated Form Objects
$form1 = New-Object System.Windows.Forms.Form
$progressBar7 = New-Object System.Windows.Forms.ProgressBar
$JRElbl = New-Object System.Windows.Forms.Label
$EMETlbl = New-Object System.Windows.Forms.Label
$FFlbl = New-Object System.Windows.Forms.Label
$SHlbl = New-Object System.Windows.Forms.Label
$FLPGlbl = New-Object System.Windows.Forms.Label
$FLAXlbl = New-Object System.Windows.Forms.Label
$RDRlbl = New-Object System.Windows.Forms.Label
$progressBar6 = New-Object System.Windows.Forms.ProgressBar
$progressBar5 = New-Object System.Windows.Forms.ProgressBar
$progressBar4 = New-Object System.Windows.Forms.ProgressBar
$progressBar3 = New-Object System.Windows.Forms.ProgressBar
$progressBar2 = New-Object System.Windows.Forms.ProgressBar
$progressBar1 = New-Object System.Windows.Forms.ProgressBar
$JREUpgr = New-Object System.Windows.Forms.Button
$JRECurrent = New-Object System.Windows.Forms.Button
$JREtxt = New-Object System.Windows.Forms.TextBox
$pictureBox7 = New-Object System.Windows.Forms.PictureBox
$pictureBox6 = New-Object System.Windows.Forms.PictureBox
$pictureBox5 = New-Object System.Windows.Forms.PictureBox
$pictureBox4 = New-Object System.Windows.Forms.PictureBox
$pictureBox3 = New-Object System.Windows.Forms.PictureBox
$pictureBox2 = New-Object System.Windows.Forms.PictureBox
$pictureBox1 = New-Object System.Windows.Forms.PictureBox
$EMETCurrent = New-Object System.Windows.Forms.Button
$FFCurrent = New-Object System.Windows.Forms.Button
$SHCurrent = New-Object System.Windows.Forms.Button
$FLPGCurrent = New-Object System.Windows.Forms.Button
$FLAXCurrent = New-Object System.Windows.Forms.Button
$RDRCurrent = New-Object System.Windows.Forms.Button
$EMETUpgr = New-Object System.Windows.Forms.Button
$FFUpgr = New-Object System.Windows.Forms.Button
$SHUpgr = New-Object System.Windows.Forms.Button
$FLPGUpgr = New-Object System.Windows.Forms.Button
$FLAXUpgr = New-Object System.Windows.Forms.Button
$RDRUpgr = New-Object System.Windows.Forms.Button
$RDRTxt = New-Object System.Windows.Forms.TextBox
$FLAXtxt = New-Object System.Windows.Forms.TextBox
$FLPGtxt = New-Object System.Windows.Forms.TextBox
$SHTxt = New-Object System.Windows.Forms.TextBox
$FFTxt = New-Object System.Windows.Forms.TextBox
$EMETtxt = New-Object System.Windows.Forms.TextBox
$InitialFormWindowState = New-Object System.Windows.Forms.FormWindowState
#endregion Generated Form Objects

#----------------------------------------------
#Generated Event Script Blocks
#----------------------------------------------
#Provide Custom Code for events specified in PrimalForms.
$FFUpgr_OnClick= 
	{
		. "<<Computer>>\desktop\SASscripts\TPTestbed\TPVariables.ps1"
		If ($FFTxt.Text -ne "") {
		(Get-Content .\TPVariables.ps1) |  foreach-object {$_.replace($RequiredVersionFF,$FFTxt.Text)} | set-content .\TPVariables.ps1
			}
	}

$FFCurrent_OnClick= 
{
#TODO: Place custom script here
. "<<Computer>>\desktop\SASscripts\TPTestbed\TPVariables.ps1"
$FFTxt.Text = $RequiredVersionFF
}

$JREUpgr_OnClick= 
{
#TODO: Place custom script here

}

$EMETUpgr_OnClick= 
	{
		. "<<Computer>>\desktop\SASscripts\TPTestbed\TPVariables.ps1"
		If ($EMETtxt.Text -ne "") {
		(Get-Content .\TPVariables.ps1) |  foreach-object {$_.replace($RequiredVersionEMET,$EMETtxt.Text)} | set-content .\TPVariables.ps1
		}
	}

$handler_pictureBox5_Click= 
{
#TODO: Place custom script here

}

$FLPGCurrent_OnClick= 
{
#TODO: Place custom script here
. "<<Computer>>\desktop\SASscripts\TPTestbed\TPVariables.ps1"
$FLPGtxt.Text = $RequiredVersionPG
}

$EMETCurrent_OnClick= 
{
#TODO: Place custom script here
. "<<Computer>>\desktop\SASscripts\TPTestbed\TPVariables.ps1"
$EMETtxt.Text = $RequiredVersionEMET
}

$FLAXUpgr_OnClick=
	{
		. "<<Computer>>\desktop\SASscripts\TPTestbed\TPVariables.ps1"
		If ($FLAXtxt.Text -ne "") {
		(Get-Content .\TPVariables.ps1) | Foreach-Object {$_.replace($RequiredVersionAX,$FLAXtxt.Text)} | set-content .\TPVariables.ps1
		}
	}

$SHCurrent_OnClick= 
{
#TODO: Place custom script here
. "<<Computer>>\desktop\SASscripts\TPTestbed\TPVariables.ps1"
$SHTxt.Text = $RequiredVersionSW
}

$RDRCurrent_OnClick= 
{
#TODO: Place custom script here
. "<<Computer>>\desktop\SASscripts\TPTestbed\TPVariables.ps1"
$RDRTxt.Text = $RequiredVersionRDR
}


$handler_form1_Load= 
{
#TODO: Place custom script here

}

$handler_pictureBox6_Click= 
{
#TODO: Place custom script here

}

$SHUpgr_OnClick= 
	{
		. "<<Computer>>\desktop\SASscripts\TPTestbed\TPVariables.ps1"
		If ($SHTxt.Text -ne "") {
		(Get-Content .\TPVariables.ps1) |  foreach-object {$_.replace($RequiredVersionSH,$SHtxt.Text)} | set-content .\TPVariables.ps1
		}
	}

$FLPGUpgr_OnClick= 
	{
		. "<<Computer>>\desktop\SASscripts\TPTestbed\TPVariables.ps1"
		If ($FLPGtxt.Text -ne "") {
		(Get-Content .\TPVariables.ps1) | Foreach-Object {$_.replace($RequiredVersionPG,$FLPGtxt.Text)} | set-content .\TPVariables.ps1
		}
	}

$JRECurrent_OnClick= 
{
#TODO: Place custom script here

}

$FLAXCurrent_OnClick= 
{
#TODO: Place custom script here
. "<<Computer>>\desktop\SASscripts\TPTestbed\TPVariables.ps1"
$FLAXtxt.Text = $RequiredVersionAX
}

$RDRUpgr_OnClick= 
	{
		. "<<Computer>>\desktop\SASscripts\TPTestbed\TPVariables.ps1"
		If ($RDRtxt.Text -ne "") {
		(Get-Content .\TPVariables.ps1) |  New-Object {$RequiredVersionRDR = $RDRTxt.Text} | set-content .\TPVariables.ps1 -Force
		}
	}

$handler_textBox1_TextChanged= 
{
#TODO: Place custom script here

}

$handler_textBox6_TextChanged= 
{
#TODO: Place custom script here

}

$OnLoadForm_StateCorrection=
{#Correct the initial state of the form to prevent the .Net maximized form issue
	$form1.WindowState = $InitialFormWindowState
}

#----------------------------------------------
#region Generated Form Code
$form1.BackgroundImage = [System.Drawing.Image]::FromFile('<<Computer>>\Pictures\Earth-On-Fire-HD-Wallpaper.jpg')
$form1.BackgroundImageLayout = 3
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 484
$System_Drawing_Size.Width = 656
$form1.ClientSize = $System_Drawing_Size
$form1.DataBindings.DefaultDataSourceUpdateMode = 0
$form1.Icon = [System.Drawing.Icon]::ExtractAssociatedIcon('<<Computer>>\Desktop\SAS_small.ico')
$form1.Name = "form1"
$form1.Text = "SAS Third Party Version Configuration"
$form1.add_Load($handler_form1_Load)

$progressBar7.DataBindings.DefaultDataSourceUpdateMode = 0
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 33
$System_Drawing_Point.Y = 454
$progressBar7.Location = $System_Drawing_Point
$progressBar7.Name = "progressBar7"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 10
$System_Drawing_Size.Width = 154
$progressBar7.Size = $System_Drawing_Size
$progressBar7.TabIndex = 47

$form1.Controls.Add($progressBar7)

$JRElbl.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 92
$System_Drawing_Point.Y = 354
$JRElbl.Location = $System_Drawing_Point
$JRElbl.Name = "JRElbl"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 95
$JRElbl.Size = $System_Drawing_Size
$JRElbl.TabIndex = 46
$JRElbl.Text = "Java Run-time"
$JRElbl.TextAlign = 32

$form1.Controls.Add($JRElbl)

$EMETlbl.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 523
$System_Drawing_Point.Y = 207
$EMETlbl.Location = $System_Drawing_Point
$EMETlbl.Name = "EMETlbl"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 100
$EMETlbl.Size = $System_Drawing_Size
$EMETlbl.TabIndex = 45
$EMETlbl.Text = "EMET"
$EMETlbl.TextAlign = 32

$form1.Controls.Add($EMETlbl)

$FFlbl.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 303
$System_Drawing_Point.Y = 207
$FFlbl.Location = $System_Drawing_Point
$FFlbl.Name = "FFlbl"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 100
$FFlbl.Size = $System_Drawing_Size
$FFlbl.TabIndex = 44
$FFlbl.Text = "Mozilla Firefox"
$FFlbl.TextAlign = 32

$form1.Controls.Add($FFlbl)

$SHlbl.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 87
$System_Drawing_Point.Y = 207
$SHlbl.Location = $System_Drawing_Point
$SHlbl.Name = "SHlbl"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 100
$SHlbl.Size = $System_Drawing_Size
$SHlbl.TabIndex = 43
$SHlbl.Text = "Adobe Shockwave"
$SHlbl.TextAlign = 32

$form1.Controls.Add($SHlbl)

$FLPGlbl.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 523
$System_Drawing_Point.Y = 49
$FLPGlbl.Location = $System_Drawing_Point
$FLPGlbl.Name = "FLPGlbl"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 100
$FLPGlbl.Size = $System_Drawing_Size
$FLPGlbl.TabIndex = 42
$FLPGlbl.Text = "Flash Plugin"
$FLPGlbl.TextAlign = 32

$form1.Controls.Add($FLPGlbl)

$FLAXlbl.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 304
$System_Drawing_Point.Y = 49
$FLAXlbl.Location = $System_Drawing_Point
$FLAXlbl.Name = "FLAXlbl"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 100
$FLAXlbl.Size = $System_Drawing_Size
$FLAXlbl.TabIndex = 41
$FLAXlbl.Text = "Flash ActiveX"
$FLAXlbl.TextAlign = 32

$form1.Controls.Add($FLAXlbl)

$RDRlbl.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 88
$System_Drawing_Point.Y = 49
$RDRlbl.Location = $System_Drawing_Point
$RDRlbl.Name = "RDRlbl"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 100
$RDRlbl.Size = $System_Drawing_Size
$RDRlbl.TabIndex = 40
$RDRlbl.Text = "Adobe Reader"
$RDRlbl.TextAlign = 32

$form1.Controls.Add($RDRlbl)

$progressBar6.DataBindings.DefaultDataSourceUpdateMode = 0
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 248
$System_Drawing_Point.Y = 143
$progressBar6.Location = $System_Drawing_Point
$progressBar6.Name = "progressBar6"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 10
$System_Drawing_Size.Width = 156
$progressBar6.Size = $System_Drawing_Size
$progressBar6.TabIndex = 39

$form1.Controls.Add($progressBar6)

$progressBar5.DataBindings.DefaultDataSourceUpdateMode = 0
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 463
$System_Drawing_Point.Y = 143
$progressBar5.Location = $System_Drawing_Point
$progressBar5.Name = "progressBar5"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 10
$System_Drawing_Size.Width = 156
$progressBar5.Size = $System_Drawing_Size
$progressBar5.TabIndex = 38

$form1.Controls.Add($progressBar5)

$progressBar4.DataBindings.DefaultDataSourceUpdateMode = 0
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 463
$System_Drawing_Point.Y = 303
$progressBar4.Location = $System_Drawing_Point
$progressBar4.Name = "progressBar4"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 10
$System_Drawing_Size.Width = 156
$progressBar4.Size = $System_Drawing_Size
$progressBar4.TabIndex = 37

$form1.Controls.Add($progressBar4)

$progressBar3.DataBindings.DefaultDataSourceUpdateMode = 0
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 248
$System_Drawing_Point.Y = 304
$progressBar3.Location = $System_Drawing_Point
$progressBar3.Name = "progressBar3"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 10
$System_Drawing_Size.Width = 156
$progressBar3.Size = $System_Drawing_Size
$progressBar3.TabIndex = 36

$form1.Controls.Add($progressBar3)

$progressBar2.DataBindings.DefaultDataSourceUpdateMode = 0
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 33
$System_Drawing_Point.Y = 304
$progressBar2.Location = $System_Drawing_Point
$progressBar2.Name = "progressBar2"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 10
$System_Drawing_Size.Width = 156
$progressBar2.Size = $System_Drawing_Size
$progressBar2.TabIndex = 35

$form1.Controls.Add($progressBar2)

$progressBar1.DataBindings.DefaultDataSourceUpdateMode = 0
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 33
$System_Drawing_Point.Y = 144
$progressBar1.Location = $System_Drawing_Point
$progressBar1.Name = "progressBar1"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 10
$System_Drawing_Size.Width = 155
$progressBar1.Size = $System_Drawing_Size
$progressBar1.TabIndex = 34

$form1.Controls.Add($progressBar1)


$JREUpgr.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 113
$System_Drawing_Point.Y = 423
$JREUpgr.Location = $System_Drawing_Point
$JREUpgr.Name = "JREUpgr"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 75
$JREUpgr.Size = $System_Drawing_Size
$JREUpgr.TabIndex = 33
$JREUpgr.Text = "Update Now"
$JREUpgr.UseVisualStyleBackColor = $True
$JREUpgr.add_Click($JREUpgr_OnClick)

$form1.Controls.Add($JREUpgr)


$JRECurrent.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 33
$System_Drawing_Point.Y = 424
$JRECurrent.Location = $System_Drawing_Point
$JRECurrent.Name = "JRECurrent"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 75
$JRECurrent.Size = $System_Drawing_Size
$JRECurrent.TabIndex = 32
$JRECurrent.Text = "Current"
$JRECurrent.UseVisualStyleBackColor = $True
$JRECurrent.add_Click($JRECurrent_OnClick)

$form1.Controls.Add($JRECurrent)

$JREtxt.BackColor = [System.Drawing.Color]::FromArgb(255,67,78,84)
$JREtxt.DataBindings.DefaultDataSourceUpdateMode = 0
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 33
$System_Drawing_Point.Y = 398
$JREtxt.Location = $System_Drawing_Point
$JREtxt.Name = "JREtxt"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 20
$System_Drawing_Size.Width = 156
$JREtxt.Size = $System_Drawing_Size
$JREtxt.TabIndex = 31

$form1.Controls.Add($JREtxt)

$pictureBox7.BackgroundImage = [System.Drawing.Image]::FromFile('<<Computer>>\Pictures\java-icon.jpg')
$pictureBox7.BackgroundImageLayout = 3
$pictureBox7.DataBindings.DefaultDataSourceUpdateMode = 0



$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 33
$System_Drawing_Point.Y = 342
$pictureBox7.Location = $System_Drawing_Point
$pictureBox7.Name = "pictureBox7"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 50
$System_Drawing_Size.Width = 52
$pictureBox7.Size = $System_Drawing_Size
$pictureBox7.TabIndex = 30
$pictureBox7.TabStop = $False

$form1.Controls.Add($pictureBox7)

$pictureBox6.BackgroundImage = [System.Drawing.Image]::FromFile('<<Computer>>\Pictures\EMET.png')
$pictureBox6.BackgroundImageLayout = 3
$pictureBox6.DataBindings.DefaultDataSourceUpdateMode = 0



$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 463
$System_Drawing_Point.Y = 192
$pictureBox6.Location = $System_Drawing_Point
$pictureBox6.Name = "pictureBox6"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 50
$System_Drawing_Size.Width = 54
$pictureBox6.Size = $System_Drawing_Size
$pictureBox6.TabIndex = 29
$pictureBox6.TabStop = $False
$pictureBox6.add_Click($handler_pictureBox6_Click)

$form1.Controls.Add($pictureBox6)

$pictureBox5.BackgroundImage = [System.Drawing.Image]::FromFile('<<Computer>>\Pictures\Firefiox-icon.jpg')
$pictureBox5.BackgroundImageLayout = 3
$pictureBox5.DataBindings.DefaultDataSourceUpdateMode = 0



$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 248
$System_Drawing_Point.Y = 192
$pictureBox5.Location = $System_Drawing_Point
$pictureBox5.Name = "pictureBox5"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 50
$System_Drawing_Size.Width = 51
$pictureBox5.Size = $System_Drawing_Size
$pictureBox5.TabIndex = 28
$pictureBox5.TabStop = $False
$pictureBox5.add_Click($handler_pictureBox5_Click)

$form1.Controls.Add($pictureBox5)

$pictureBox4.BackgroundImage = [System.Drawing.Image]::FromFile('<<Computer>>\Pictures\Adobe-Shockwave-icon.jpg')
$pictureBox4.BackgroundImageLayout = 3
$pictureBox4.DataBindings.DefaultDataSourceUpdateMode = 0



$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 33
$System_Drawing_Point.Y = 192
$pictureBox4.Location = $System_Drawing_Point
$pictureBox4.Name = "pictureBox4"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 50
$System_Drawing_Size.Width = 52
$pictureBox4.Size = $System_Drawing_Size
$pictureBox4.TabIndex = 27
$pictureBox4.TabStop = $False

$form1.Controls.Add($pictureBox4)

$pictureBox3.BackgroundImage = [System.Drawing.Image]::FromFile('<<Computer>>\Pictures\Adobe-Flash-icon.jpg')
$pictureBox3.BackgroundImageLayout = 3
$pictureBox3.DataBindings.DefaultDataSourceUpdateMode = 0



$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 463
$System_Drawing_Point.Y = 32
$pictureBox3.Location = $System_Drawing_Point
$pictureBox3.Name = "pictureBox3"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 50
$System_Drawing_Size.Width = 54
$pictureBox3.Size = $System_Drawing_Size
$pictureBox3.TabIndex = 26
$pictureBox3.TabStop = $False

$form1.Controls.Add($pictureBox3)

$pictureBox2.BackgroundImage = [System.Drawing.Image]::FromFile('<<Computer>>\Pictures\Adobe-Flash-icon.jpg')
$pictureBox2.BackgroundImageLayout = 3
$pictureBox2.DataBindings.DefaultDataSourceUpdateMode = 0



$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 248
$System_Drawing_Point.Y = 32
$pictureBox2.Location = $System_Drawing_Point
$pictureBox2.Name = "pictureBox2"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 50
$System_Drawing_Size.Width = 51
$pictureBox2.Size = $System_Drawing_Size
$pictureBox2.TabIndex = 25
$pictureBox2.TabStop = $False

$form1.Controls.Add($pictureBox2)

$pictureBox1.BackgroundImage = [System.Drawing.Image]::FromFile('<<Computer>>\Pictures\Adobe-Acrobat-Reader-icon.png')
$pictureBox1.BackgroundImageLayout = 3
$pictureBox1.DataBindings.DefaultDataSourceUpdateMode = 0



$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 33
$System_Drawing_Point.Y = 32
$pictureBox1.Location = $System_Drawing_Point
$pictureBox1.Name = "pictureBox1"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 50
$System_Drawing_Size.Width = 52
$pictureBox1.Size = $System_Drawing_Size
$pictureBox1.TabIndex = 24
$pictureBox1.TabStop = $False

$form1.Controls.Add($pictureBox1)


$EMETCurrent.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 463
$System_Drawing_Point.Y = 274
$EMETCurrent.Location = $System_Drawing_Point
$EMETCurrent.Name = "EMETCurrent"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 75
$EMETCurrent.Size = $System_Drawing_Size
$EMETCurrent.TabIndex = 23
$EMETCurrent.Text = "Current"
$EMETCurrent.UseVisualStyleBackColor = $True
$EMETCurrent.add_Click($EMETCurrent_OnClick)

$form1.Controls.Add($EMETCurrent)


$FFCurrent.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 248
$System_Drawing_Point.Y = 274
$FFCurrent.Location = $System_Drawing_Point
$FFCurrent.Name = "FFCurrent"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 75
$FFCurrent.Size = $System_Drawing_Size
$FFCurrent.TabIndex = 22
$FFCurrent.Text = "Current"
$FFCurrent.UseVisualStyleBackColor = $True
$FFCurrent.add_Click($FFCurrent_OnClick)

$form1.Controls.Add($FFCurrent)


$SHCurrent.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 33
$System_Drawing_Point.Y = 274
$SHCurrent.Location = $System_Drawing_Point
$SHCurrent.Name = "SHCurrent"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 75
$SHCurrent.Size = $System_Drawing_Size
$SHCurrent.TabIndex = 21
$SHCurrent.Text = "Current"
$SHCurrent.UseVisualStyleBackColor = $True
$SHCurrent.add_Click($SHCurrent_OnClick)

$form1.Controls.Add($SHCurrent)


$FLPGCurrent.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 463
$System_Drawing_Point.Y = 114
$FLPGCurrent.Location = $System_Drawing_Point
$FLPGCurrent.Name = "FLPGCurrent"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 75
$FLPGCurrent.Size = $System_Drawing_Size
$FLPGCurrent.TabIndex = 20
$FLPGCurrent.Text = "Current"
$FLPGCurrent.UseVisualStyleBackColor = $True
$FLPGCurrent.add_Click($FLPGCurrent_OnClick)

$form1.Controls.Add($FLPGCurrent)


$FLAXCurrent.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 248
$System_Drawing_Point.Y = 114
$FLAXCurrent.Location = $System_Drawing_Point
$FLAXCurrent.Name = "FLAXCurrent"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 75
$FLAXCurrent.Size = $System_Drawing_Size
$FLAXCurrent.TabIndex = 19
$FLAXCurrent.Text = "Current"
$FLAXCurrent.UseVisualStyleBackColor = $True
$FLAXCurrent.add_Click($FLAXCurrent_OnClick)

$form1.Controls.Add($FLAXCurrent)


$RDRCurrent.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 33
$System_Drawing_Point.Y = 114
$RDRCurrent.Location = $System_Drawing_Point
$RDRCurrent.Name = "RDRCurrent"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 75
$RDRCurrent.Size = $System_Drawing_Size
$RDRCurrent.TabIndex = 18
$RDRCurrent.Text = "Current"
$RDRCurrent.UseVisualStyleBackColor = $True
$RDRCurrent.add_Click($RDRCurrent_OnClick)

$form1.Controls.Add($RDRCurrent)


$EMETUpgr.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 544
$System_Drawing_Point.Y = 274
$EMETUpgr.Location = $System_Drawing_Point
$EMETUpgr.Name = "EMETUpgr"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 75
$EMETUpgr.Size = $System_Drawing_Size
$EMETUpgr.TabIndex = 17
$EMETUpgr.Text = "Update Now"
$EMETUpgr.UseVisualStyleBackColor = $True
$EMETUpgr.add_Click($EMETUpgr_OnClick)

$form1.Controls.Add($EMETUpgr)


$FFUpgr.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 329
$System_Drawing_Point.Y = 274
$FFUpgr.Location = $System_Drawing_Point
$FFUpgr.Name = "FFUpgr"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 75
$FFUpgr.Size = $System_Drawing_Size
$FFUpgr.TabIndex = 16
$FFUpgr.Text = "Update Now"
$FFUpgr.UseVisualStyleBackColor = $True
$FFUpgr.add_Click($FFUpgr_OnClick)

$form1.Controls.Add($FFUpgr)


$SHUpgr.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 114
$System_Drawing_Point.Y = 274
$SHUpgr.Location = $System_Drawing_Point
$SHUpgr.Name = "SHUpgr"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 75
$SHUpgr.Size = $System_Drawing_Size
$SHUpgr.TabIndex = 15
$SHUpgr.Text = "Update Now"
$SHUpgr.UseVisualStyleBackColor = $True
$SHUpgr.add_Click($SHUpgr_OnClick)

$form1.Controls.Add($SHUpgr)


$FLPGUpgr.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 544
$System_Drawing_Point.Y = 114
$FLPGUpgr.Location = $System_Drawing_Point
$FLPGUpgr.Name = "FLPGUpgr"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 75
$FLPGUpgr.Size = $System_Drawing_Size
$FLPGUpgr.TabIndex = 14
$FLPGUpgr.Text = "Update Now"
$FLPGUpgr.UseVisualStyleBackColor = $True
$FLPGUpgr.add_Click($FLPGUpgr_OnClick)

$form1.Controls.Add($FLPGUpgr)


$FLAXUpgr.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 329
$System_Drawing_Point.Y = 114
$FLAXUpgr.Location = $System_Drawing_Point
$FLAXUpgr.Name = "FLAXUpgr"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 75
$FLAXUpgr.Size = $System_Drawing_Size
$FLAXUpgr.TabIndex = 13
$FLAXUpgr.Text = "Update Now"
$FLAXUpgr.UseVisualStyleBackColor = $True
$FLAXUpgr.add_Click($FLAXUpgr_OnClick)

$form1.Controls.Add($FLAXUpgr)


$RDRUpgr.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 114
$System_Drawing_Point.Y = 114
$RDRUpgr.Location = $System_Drawing_Point
$RDRUpgr.Name = "RDRUpgr"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 75
$RDRUpgr.Size = $System_Drawing_Size
$RDRUpgr.TabIndex = 12
$RDRUpgr.Text = "Update Now"
$RDRUpgr.UseVisualStyleBackColor = $True
$RDRUpgr.add_Click($RDRUpgr_OnClick)

$form1.Controls.Add($RDRUpgr)

$RDRTxt.BackColor = [System.Drawing.Color]::FromArgb(255,67,78,84)
$RDRTxt.DataBindings.DefaultDataSourceUpdateMode = 0
$RDRTxt.ForeColor = [System.Drawing.Color]::FromArgb(255,255,255,225)
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 33
$System_Drawing_Point.Y = 88
$RDRTxt.Location = $System_Drawing_Point
$RDRTxt.Name = "RDRTxt"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 20
$System_Drawing_Size.Width = 156
$RDRTxt.Size = $System_Drawing_Size
$RDRTxt.TabIndex = 11
$RDRTxt.add_TextChanged($handler_textBox6_TextChanged)

$form1.Controls.Add($RDRTxt)

$FLAXtxt.BackColor = [System.Drawing.Color]::FromArgb(255,67,78,84)
$FLAXtxt.DataBindings.DefaultDataSourceUpdateMode = 0
$FLAXtxt.ForeColor = [System.Drawing.Color]::FromArgb(255,255,255,225)
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 248
$System_Drawing_Point.Y = 88
$FLAXtxt.Location = $System_Drawing_Point
$FLAXtxt.Name = "FLAXtxt"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 20
$System_Drawing_Size.Width = 156
$FLAXtxt.Size = $System_Drawing_Size
$FLAXtxt.TabIndex = 10

$form1.Controls.Add($FLAXtxt)

$FLPGtxt.BackColor = [System.Drawing.Color]::FromArgb(255,67,78,84)
$FLPGtxt.DataBindings.DefaultDataSourceUpdateMode = 0
$FLPGTxt.ForeColor = [System.Drawing.Color]::FromArgb(255,255,255,225)
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 463
$System_Drawing_Point.Y = 88
$FLPGtxt.Location = $System_Drawing_Point
$FLPGtxt.Name = "FLPGtxt"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 20
$System_Drawing_Size.Width = 156
$FLPGtxt.Size = $System_Drawing_Size
$FLPGtxt.TabIndex = 9

$form1.Controls.Add($FLPGtxt)

$SHTxt.BackColor = [System.Drawing.Color]::FromArgb(255,67,78,84)
$SHTxt.DataBindings.DefaultDataSourceUpdateMode = 0
$SHTxt.ForeColor = [System.Drawing.Color]::FromArgb(255,255,255,225)
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 33
$System_Drawing_Point.Y = 248
$SHTxt.Location = $System_Drawing_Point
$SHTxt.Name = "SHTxt"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 20
$System_Drawing_Size.Width = 156
$SHTxt.Size = $System_Drawing_Size
$SHTxt.TabIndex = 8

$form1.Controls.Add($SHTxt)

$FFTxt.BackColor = [System.Drawing.Color]::FromArgb(255,67,78,84)
$FFTxt.DataBindings.DefaultDataSourceUpdateMode = 0
$FFTxt.ForeColor = [System.Drawing.Color]::FromArgb(255,255,255,225)
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 248
$System_Drawing_Point.Y = 248
$FFTxt.Location = $System_Drawing_Point
$FFTxt.Name = "FFTxt"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 20
$System_Drawing_Size.Width = 156
$FFTxt.Size = $System_Drawing_Size
$FFTxt.TabIndex = 7

$form1.Controls.Add($FFTxt)

$EMETtxt.BackColor = [System.Drawing.Color]::FromArgb(255,67,78,84)
$EMETtxt.DataBindings.DefaultDataSourceUpdateMode = 0
$EMETTxt.ForeColor = [System.Drawing.Color]::FromArgb(255,255,255,225)
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 463
$System_Drawing_Point.Y = 248
$EMETtxt.Location = $System_Drawing_Point
$EMETtxt.Name = "EMETtxt"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 20
$System_Drawing_Size.Width = 156
$EMETtxt.Size = $System_Drawing_Size
$EMETtxt.TabIndex = 6
$EMETtxt.add_TextChanged($handler_textBox1_TextChanged)

$form1.Controls.Add($EMETtxt)

#endregion Generated Form Code

#Save the initial state of the form
$InitialFormWindowState = $form1.WindowState
#Init the OnLoad event to correct the initial state of the form
$form1.add_Load($OnLoadForm_StateCorrection)
#Show the Form
$form1.ShowDialog()| Out-Null

} #End Function

#Call the Function
GenerateForm