#Generated Form Function
function GenerateForm {
########################################################################
# Code Generated By: SAPIEN Technologies PrimalForms (Community Edition) v1.0.10.0
# Generated On: 3/20/2014 8:41 AM
# Generated By: smithsa
########################################################################

#region Import the Assemblies
[reflection.assembly]::loadwithpartialname("System.Drawing") | Out-Null
[reflection.assembly]::loadwithpartialname("System.Windows.Forms") | Out-Null
#endregion

#region Generated Form Objects
$form1 = New-Object System.Windows.Forms.Form
$tabControl1 = New-Object System.Windows.Forms.TabControl
$tabPage1 = New-Object System.Windows.Forms.TabPage
$panel5 = New-Object System.Windows.Forms.Panel
$uptimebutt = New-Object System.Windows.Forms.Button
$totaluptimetxt = New-Object System.Windows.Forms.TextBox
$uptimenametxt = New-Object System.Windows.Forms.TextBox
$label1 = New-Object System.Windows.Forms.Label
$panel4 = New-Object System.Windows.Forms.Panel
$TranslateTxt = New-Object System.Windows.Forms.TextBox
$SIDTransBut = New-Object System.Windows.Forms.Button
$SIDtxt = New-Object System.Windows.Forms.TextBox
$SIDlbl = New-Object System.Windows.Forms.Label
$panel3 = New-Object System.Windows.Forms.Panel
$LocalAdminTxt = New-Object System.Windows.Forms.TextBox
$SearchMachButt = New-Object System.Windows.Forms.Button
$AdminBox = New-Object System.Windows.Forms.ListBox
$LocalAdminlbl = New-Object System.Windows.Forms.Label
$panel1 = New-Object System.Windows.Forms.Panel
$GetLockedUsers = New-Object System.Windows.Forms.Button
$Lockoutlbl = New-Object System.Windows.Forms.Label
$LockedBox = New-Object System.Windows.Forms.ListBox
$UnlockAll = New-Object System.Windows.Forms.Button
$UnlockAccounts = New-Object System.Windows.Forms.Button
$tabPage2 = New-Object System.Windows.Forms.TabPage
$panel2 = New-Object System.Windows.Forms.Panel
$TPVersionLBL = New-Object System.Windows.Forms.Label
$label9 = New-Object System.Windows.Forms.Label
$EMETlbl = New-Object System.Windows.Forms.Label
$FLPGlbl = New-Object System.Windows.Forms.Label
$label6 = New-Object System.Windows.Forms.Label
$FFlbl = New-Object System.Windows.Forms.Label
$FLAXlbl = New-Object System.Windows.Forms.Label
$JRElbl = New-Object System.Windows.Forms.Label
$SHlbl = New-Object System.Windows.Forms.Label
$RDRlbl = New-Object System.Windows.Forms.Label
$button21 = New-Object System.Windows.Forms.Button
$EMETUpgr = New-Object System.Windows.Forms.Button
$FLPGUpgr = New-Object System.Windows.Forms.Button
$button18 = New-Object System.Windows.Forms.Button
$EMETCurrent = New-Object System.Windows.Forms.Button
$FLPGCurrent = New-Object System.Windows.Forms.Button
$button15 = New-Object System.Windows.Forms.Button
$FFUpgr = New-Object System.Windows.Forms.Button
$FLAXUpgr = New-Object System.Windows.Forms.Button
$button12 = New-Object System.Windows.Forms.Button
$FFCurrent = New-Object System.Windows.Forms.Button
$FLAXCurrent = New-Object System.Windows.Forms.Button
$JREUpgr = New-Object System.Windows.Forms.Button
$SHUpgr = New-Object System.Windows.Forms.Button
$RDRUpgr = New-Object System.Windows.Forms.Button
$textBox9 = New-Object System.Windows.Forms.TextBox
$EMETtxt = New-Object System.Windows.Forms.TextBox
$FLPGtxt = New-Object System.Windows.Forms.TextBox
$textBox6 = New-Object System.Windows.Forms.TextBox
$FFtxt = New-Object System.Windows.Forms.TextBox
$FLAXtxt = New-Object System.Windows.Forms.TextBox
$pictureBox9 = New-Object System.Windows.Forms.PictureBox
$pictureBox8 = New-Object System.Windows.Forms.PictureBox
$pictureBox7 = New-Object System.Windows.Forms.PictureBox
$pictureBox6 = New-Object System.Windows.Forms.PictureBox
$pictureBox5 = New-Object System.Windows.Forms.PictureBox
$pictureBox4 = New-Object System.Windows.Forms.PictureBox
$JRECurrent = New-Object System.Windows.Forms.Button
$SHCurrent = New-Object System.Windows.Forms.Button
$RDRCurrent = New-Object System.Windows.Forms.Button
$pictureBox3 = New-Object System.Windows.Forms.PictureBox
$pictureBox2 = New-Object System.Windows.Forms.PictureBox
$pictureBox1 = New-Object System.Windows.Forms.PictureBox
$SHtxt = New-Object System.Windows.Forms.TextBox
$JREtxt = New-Object System.Windows.Forms.TextBox
$RDRtxt = New-Object System.Windows.Forms.TextBox
$toolBar1 = New-Object System.Windows.Forms.ToolBar
$timer1 = New-Object System.Windows.Forms.Timer
$InitialFormWindowState = New-Object System.Windows.Forms.FormWindowState
#endregion Generated Form Objects

#----------------------------------------------
#Generated Event Script Blocks
#----------------------------------------------
#Provide Custom Code for events specified in PrimalForms.
$SearchMachButt_OnClick= 
{
	IF(-not $Append)
		{
			$AdminBox.items.clear()
		}
	
	
	$SASmach = $LocalAdmintxt.text 
	$Result = @()	
	
	If (Test-Connection -comp $SASmach -count 1)
		{
			
			$computer = [ADSI]("WinNT://"+ $SASmach + ",computer")
			$Group = $computer.psbase.children.find("Administrators")
			function getAdmins
			{
				$members = ($Group.psbase.invoke("Members") | %{$_.GetType().invokemember("Adspath",'GetProperty',$null,$_,$null)}) -replace ('WinNT://DOMAIN/' + $SASmach + '/'), ''-replace ('WinNT://DOMAIN/','DOMAIN\') -replace ('WinNT://','') 
				$members}
				$Result += (getAdmins)
										
				<#Foreach ($Result2 in $members)
				{
					$Adminbox.Items.add($Result2)
				}
			#>
			
		}
	Else 
		{
			[System.Windows.Forms.MessageBox]::Show("SAS Machine is Offline or cannot be found. Please check your spelling and try again.","Hmmm...Nothing Found",0)
		}
	Foreach ($user in $Result)
		{
			$AdminBox.Items.Add($User)
		}
	

}

$FFUpgr_OnClick= 
{


}

$uptimebutt_OnClick= 
{
	$Computer = $UptimeNametxt.Text

	If (Test-Connection -comp $Computer  -count 1)
	{
		$lastbootime = (Get-WMIObject -class Win32_OperatingSystem -computername $Computer).LastbootUpTime
		$sysuptime = (Get-Date) - [System.Management.ManagementDateTimeconverter]::ToDateTime($lastbootime)
		$totaluptime = "  $Computer has been up for: ",$sysuptime.days ,"days ",$sysuptime.hours,"hours ",$sysuptime.minutes, "minutes",$sysuptime.seconds,"seconds"
		$totaluptimetxt.Text = $totaluptime
	}
	else
		{
			[System.Windows.Forms.MessageBox]::Show("SAS Machine is Offline or cannot be found. Please check your spelling and try again.","Hmmm...Nothing Found",0)
		}
}

$handler_textBox3_TextChanged= 
{
#TODO: Place custom script here

}

$handler_panel1_Paint= 
{
#TODO: Place custom script here

}

$JREUpgr_OnClick= 
{
#TODO: Place custom script here

}

$EMETUpgr_OnClick= 
{
#TODO: Place custom script here

}

$FLPGCurrent_OnClick= 
{
. "<<Computer>>\desktop\SASscripts\GUI-Testbed\TPVariables.ps1"
$FLPGtxt.Text = $RequiredVersionPG

}

$button15_OnClick= 
{
#TODO: Place custom script here

}

$EMETCurrent_OnClick= 
{
. "<<Computer>>\desktop\SASscripts\GUI-Testbed\TPVariables.ps1"
$EMETtxt.Text = $RequiredVersionEMET

}

$FLAXUpgr_OnClick= 
{
#TODO: Place custom script here

}

$FLAXCurrent_OnClick= 
{
. "<<Computer>>\desktop\SASscripts\GUI-Testbed\TPVariables.ps1"
$FLAXtxt.Text = $RequiredVersionAX

}

$button12_OnClick= 
{
#TODO: Place custom script here

}

$UnlockAll_OnClick= 
{
	
		$Account = $LockedBox.Text
		$Confirm = [System.Windows.Forms.MessageBox]::Show("Would you like to Unlock All Locked Out Accounts?", "Are you sure?",4)
		If ($Confirm -eq "YES")
			{
				Foreach($Forgetter2 in $LockedBox.items)
					{
						Unlock-ADAccount -Identity $Forgetter2
						
					}
				$Complete = [System.Windows.Forms.MessageBox]::Show("$Account Unlocked!" , "Complete!",0)
				$Complete	
				$LockedBox.Items.Clear()
			}

}

$JRECurrent_OnClick= 
{
#TODO: Place custom script here

}

$button21_OnClick= 
{
#TODO: Place custom script here

}

$UnlockAccounts_OnClick= 
{
		If ($LockedBox.SelectedIndex -ge 0)
			{
				$Account = $LockedBox.Text
				$Confirm = [System.Windows.Forms.MessageBox]::Show("Would you like to Unlock Account: $Account" , "Are you sure?",4)
		
				If ($Confirm -eq "YES" -and $LockedBox.SelectedIndex -ge 0)
				{
					$Name = $LockedBox.SelectedItem
					Unlock-ADAccount $Name
					$Complete = [System.Windows.Forms.MessageBox]::Show("$Account Unlocked!" , "Complete!",0)
					$Complete
				}
			}
		Elseif ($LockedBox.SelectedIndex -lt 0)
			{
				[System.Windows.Forms.MessageBox]::Show("No Item Selected!","Unh Unh Unh, You didn't say the magic word!",0,[Windows.Forms.MessageBoxIcon]::Warning)
			}

}

$RDRCurrent_OnClick= 
{
. "<<Computer>>\desktop\SASscripts\GUI-Testbed\TPVariables.ps1"
$RDRTxt.Text = $RequiredVersionRDR

}

$SHUpgr_OnClick= 
{
#TODO: Place custom script here

}

$FLPGUpgr_OnClick= 
{
#TODO: Place custom script here

}

$button18_OnClick= 
{
#TODO: Place custom script here

}

$SIDTransBut_OnClick= 
{
	If($SIDtxt.text -eq "")
	{
		[System.Windows.Forms.MessageBox]::Show("Please Enter a SID to Continue","Don't be THAT guy!",0)
	}
		$Translated = $SIDtxt.Text
		$objSID = New-Object system.security.principal.SecurityIdentifier ($Translated)
		$objUser = $objSID.Translate([System.Security.Principal.NTAccount])
		$TranslateTxt.Text = $objUser.value 
		If ($SIDtxt.text -ne "" -and $TranslateTxt.Text -eq "")
		{
			[System.Windows.Forms.MessageBox]::Show("No results found. Please check your SID and try again.","Sorry Buddy",0)
		}

}

$handler_textBox1_TextChanged= 
{
#TODO: Place custom script here

}

$RDRUpgr_OnClick= 
{
#TODO: Place custom script here

}

$SHCurrent_OnClick= 
{
.  "<<Computer>>\desktop\SASscripts\GUI-Testbed\TPVariables.ps1"
$SHTxt.Text = $RequiredVersionSW
}

$FFCurrent_OnClick= 
{
. "<<Computer>>\desktop\SASscripts\GUI-Testbed\TPVariables.ps1"
$FFTxt.Text = $RequiredVersionFF
}

$GetLockedUsers_OnClick= 
{
			If(-not $Append) 
		{
			$LockedBox.items.Clear()
		}
			$LockedUsers = Search-ADAccount -LockedOut | Select -Expand 'SAMAccountName'
			#$NoLockout =  [System.Windows.Forms.MessageBox]::Show("No SAS Users locked out at this time. Hooray!!!!!!","Remembering Passwords For the Win!",0)	
				If ($LockedUsers -eq $Null)
				{
					 [System.Windows.Forms.MessageBox]::Show("No SAS Users locked out at this time. Hooray!!!!!!","Remembering Passwords For the Win!",0)	
				}	
				Else 
				{
					foreach($Forgetter in $LockedUsers)
					{	
						$LockedBox.Items.Add($Forgetter)
					}
				}

}

$handler_textBox2_TextChanged= 
{
#TODO: Place custom script here

}

$OnLoadForm_StateCorrection=
{#Correct the initial state of the form to prevent the .Net maximized form issue
	$form1.WindowState = $InitialFormWindowState
}

#----------------------------------------------
#region Generated Form Code
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 862
$System_Drawing_Size.Width = 1089
$form1.ClientSize = $System_Drawing_Size
$form1.DataBindings.DefaultDataSourceUpdateMode = 0
$form1.Name = "form1"
$form1.Text = "SAS Sys Admin Console"

$tabControl1.DataBindings.DefaultDataSourceUpdateMode = 0
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 0
$System_Drawing_Point.Y = 48
$tabControl1.Location = $System_Drawing_Point
$tabControl1.Name = "tabControl1"
$tabControl1.SelectedIndex = 0
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 817
$System_Drawing_Size.Width = 1089
$tabControl1.Size = $System_Drawing_Size
$tabControl1.TabIndex = 1

$form1.Controls.Add($tabControl1)
$tabPage1.BackColor = [System.Drawing.Color]::FromArgb(255,105,105,105)
$tabPage1.DataBindings.DefaultDataSourceUpdateMode = 0
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 4
$System_Drawing_Point.Y = 22
$tabPage1.Location = $System_Drawing_Point
$tabPage1.Name = "tabPage1"
$System_Windows_Forms_Padding = New-Object System.Windows.Forms.Padding
$System_Windows_Forms_Padding.All = 3
$System_Windows_Forms_Padding.Bottom = 3
$System_Windows_Forms_Padding.Left = 3
$System_Windows_Forms_Padding.Right = 3
$System_Windows_Forms_Padding.Top = 3
$tabPage1.Padding = $System_Windows_Forms_Padding
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 791
$System_Drawing_Size.Width = 1081
$tabPage1.Size = $System_Drawing_Size
$tabPage1.TabIndex = 0
$tabPage1.Text = "tabPage1"

$tabControl1.Controls.Add($tabPage1)
$panel5.BackColor = [System.Drawing.Color]::FromArgb(255,192,192,192)

$panel5.DataBindings.DefaultDataSourceUpdateMode = 0
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 6
$System_Drawing_Point.Y = 6
$panel5.Location = $System_Drawing_Point
$panel5.Name = "panel5"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 157
$System_Drawing_Size.Width = 407
$panel5.Size = $System_Drawing_Size
$panel5.TabIndex = 1

$tabPage1.Controls.Add($panel5)

$uptimebutt.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 218
$System_Drawing_Point.Y = 60
$uptimebutt.Location = $System_Drawing_Point
$uptimebutt.Name = "uptimebutt"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 116
$uptimebutt.Size = $System_Drawing_Size
$uptimebutt.TabIndex = 3
$uptimebutt.Text = "Query UpTime"
$uptimebutt.UseVisualStyleBackColor = $True
$uptimebutt.add_Click($uptimebutt_OnClick)

$panel5.Controls.Add($uptimebutt)

$totaluptimetxt.DataBindings.DefaultDataSourceUpdateMode = 0
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 24
$System_Drawing_Point.Y = 96
$totaluptimetxt.Location = $System_Drawing_Point
$totaluptimetxt.Name = "totaluptimetxt"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 20
$System_Drawing_Size.Width = 368
$totaluptimetxt.Size = $System_Drawing_Size
$totaluptimetxt.TabIndex = 2
$totaluptimetxt.Text = "Total Uptime"

$panel5.Controls.Add($totaluptimetxt)

$uptimenametxt.DataBindings.DefaultDataSourceUpdateMode = 0
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 24
$System_Drawing_Point.Y = 63
$uptimenametxt.Location = $System_Drawing_Point
$uptimenametxt.Name = "uptimenametxt"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 20
$System_Drawing_Size.Width = 184
$uptimenametxt.Size = $System_Drawing_Size
$uptimenametxt.TabIndex = 1
$uptimenametxt.Text = "Enter Computer Name"
$uptimenametxt.TextAlign = 2

$panel5.Controls.Add($uptimenametxt)

$label1.BorderStyle = 2
$label1.DataBindings.DefaultDataSourceUpdateMode = 0
$label1.Font = New-Object System.Drawing.Font("Bookman Old Style",12,1,3,1)

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 24
$System_Drawing_Point.Y = 21
$label1.Location = $System_Drawing_Point
$label1.Name = "label1"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 323
$label1.Size = $System_Drawing_Size
$label1.TabIndex = 0
$label1.Text = "SAS System Uptime"
$label1.TextAlign = 32

$panel5.Controls.Add($label1)


$panel4.BackColor = [System.Drawing.Color]::FromArgb(255,200,200,200)

$panel4.DataBindings.DefaultDataSourceUpdateMode = 0
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 419
$System_Drawing_Point.Y = 8
$panel4.Location = $System_Drawing_Point
$panel4.Name = "panel4"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 155
$System_Drawing_Size.Width = 366
$panel4.Size = $System_Drawing_Size
$panel4.TabIndex = 0

$tabPage1.Controls.Add($panel4)
$TranslateTxt.DataBindings.DefaultDataSourceUpdateMode = 0
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 72
$System_Drawing_Point.Y = 122
$TranslateTxt.Location = $System_Drawing_Point
$TranslateTxt.Name = "TranslateTxt"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 20
$System_Drawing_Size.Width = 226
$TranslateTxt.Size = $System_Drawing_Size
$TranslateTxt.TabIndex = 3
$TranslateTxt.TextAlign = 2

$panel4.Controls.Add($TranslateTxt)


$SIDTransBut.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 125
$System_Drawing_Point.Y = 93
$SIDTransBut.Location = $System_Drawing_Point
$SIDTransBut.Name = "SIDTransBut"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 120
$SIDTransBut.Size = $System_Drawing_Size
$SIDTransBut.TabIndex = 2
$SIDTransBut.Text = "Translate!"
$SIDTransBut.UseVisualStyleBackColor = $True
$SIDTransBut.add_Click($SIDTransBut_OnClick)

$panel4.Controls.Add($SIDTransBut)

$SIDtxt.DataBindings.DefaultDataSourceUpdateMode = 0
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 19
$System_Drawing_Point.Y = 61
$SIDtxt.Location = $System_Drawing_Point
$SIDtxt.Name = "SIDtxt"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 20
$System_Drawing_Size.Width = 327
$SIDtxt.Size = $System_Drawing_Size
$SIDtxt.TabIndex = 1
$SIDtxt.Text = "Enter SID here"
$SIDtxt.TextAlign = 2

$panel4.Controls.Add($SIDtxt)

$SIDlbl.BorderStyle = 2
$SIDlbl.DataBindings.DefaultDataSourceUpdateMode = 0
$SIDlbl.Font = New-Object System.Drawing.Font("Bookman Old Style",12,1,3,1)

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 19
$System_Drawing_Point.Y = 21
$SIDlbl.Location = $System_Drawing_Point
$SIDlbl.Name = "SIDlbl"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 327
$SIDlbl.Size = $System_Drawing_Size
$SIDlbl.TabIndex = 0
$SIDlbl.Text = "SID to Domain User Translator"
$SIDlbl.TextAlign = 32

$panel4.Controls.Add($SIDlbl)


$panel3.BackColor = [System.Drawing.Color]::FromArgb(255,200,200,200)

$panel3.DataBindings.DefaultDataSourceUpdateMode = 0
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 6
$System_Drawing_Point.Y = 169
$panel3.Location = $System_Drawing_Point
$panel3.Name = "panel3"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 173
$System_Drawing_Size.Width = 347
$panel3.Size = $System_Drawing_Size
$panel3.TabIndex = 0

$tabPage1.Controls.Add($panel3)
$LocalAdminTxt.DataBindings.DefaultDataSourceUpdateMode = 0
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 215
$System_Drawing_Point.Y = 77
$LocalAdminTxt.Location = $System_Drawing_Point
$LocalAdminTxt.Name = "LocalAdminTxt"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 20
$System_Drawing_Size.Width = 120
$LocalAdminTxt.Size = $System_Drawing_Size
$LocalAdminTxt.TabIndex = 1
$LocalAdminTxt.Text = "Enter Computer Name"
$LocalAdminTxt.TextAlign = 2

$panel3.Controls.Add($LocalAdminTxt)


$SearchMachButt.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 215
$System_Drawing_Point.Y = 103
$SearchMachButt.Location = $System_Drawing_Point
$SearchMachButt.Name = "SearchMachButt"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 120
$SearchMachButt.Size = $System_Drawing_Size
$SearchMachButt.TabIndex = 2
$SearchMachButt.Text = "Search Machines"
$SearchMachButt.UseVisualStyleBackColor = $True
$SearchMachButt.add_Click($SearchMachButt_OnClick)

$panel3.Controls.Add($SearchMachButt)

$AdminBox.DataBindings.DefaultDataSourceUpdateMode = 0
$AdminBox.FormattingEnabled = $True
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 12
$System_Drawing_Point.Y = 47
$AdminBox.Location = $System_Drawing_Point
$AdminBox.Name = "AdminBox"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 108
$System_Drawing_Size.Width = 197
$AdminBox.Size = $System_Drawing_Size
$AdminBox.TabIndex = 0

$panel3.Controls.Add($AdminBox)

$LocalAdminlbl.BorderStyle = 2
$LocalAdminlbl.DataBindings.DefaultDataSourceUpdateMode = 0
$LocalAdminlbl.Font = New-Object System.Drawing.Font("Bookman Old Style",12,1,3,1)

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 44
$System_Drawing_Point.Y = 12
$LocalAdminlbl.Location = $System_Drawing_Point
$LocalAdminlbl.Name = "LocalAdminlbl"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 291
$LocalAdminlbl.Size = $System_Drawing_Size
$LocalAdminlbl.TabIndex = 0
$LocalAdminlbl.Text = "SAS Local Admins Search"
$LocalAdminlbl.TextAlign = 32

$panel3.Controls.Add($LocalAdminlbl)


$panel1.BackColor = [System.Drawing.Color]::FromArgb(255,200,200,200)

$panel1.DataBindings.DefaultDataSourceUpdateMode = 0
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 6
$System_Drawing_Point.Y = 353
$panel1.Location = $System_Drawing_Point
$panel1.Name = "panel1"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 173
$System_Drawing_Size.Width = 347
$panel1.Size = $System_Drawing_Size
$panel1.TabIndex = 0
$panel1.add_Paint($handler_panel1_Paint)

$tabPage1.Controls.Add($panel1)

$GetLockedUsers.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 214
$System_Drawing_Point.Y = 62
$GetLockedUsers.Location = $System_Drawing_Point
$GetLockedUsers.Name = "GetLockedUsers"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 120
$GetLockedUsers.Size = $System_Drawing_Size
$GetLockedUsers.TabIndex = 1
$GetLockedUsers.Text = "Get Locked Users"
$GetLockedUsers.UseVisualStyleBackColor = $True
$GetLockedUsers.add_Click($GetLockedUsers_OnClick)

$panel1.Controls.Add($GetLockedUsers)

$Lockoutlbl.BorderStyle = 2
$Lockoutlbl.DataBindings.DefaultDataSourceUpdateMode = 0
$Lockoutlbl.Font = New-Object System.Drawing.Font("Bookman Old Style",12,1,3,1)

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 44
$System_Drawing_Point.Y = 10
$Lockoutlbl.Location = $System_Drawing_Point
$Lockoutlbl.Name = "Lockoutlbl"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 291
$Lockoutlbl.Size = $System_Drawing_Size
$Lockoutlbl.TabIndex = 0
$Lockoutlbl.Text = "SAS Account Unlocker"
$Lockoutlbl.TextAlign = 32

$panel1.Controls.Add($Lockoutlbl)

$LockedBox.DataBindings.DefaultDataSourceUpdateMode = 0
$LockedBox.FormattingEnabled = $True
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 6
$System_Drawing_Point.Y = 47
$LockedBox.Location = $System_Drawing_Point
$LockedBox.Name = "LockedBox"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 108
$System_Drawing_Size.Width = 202
$LockedBox.Size = $System_Drawing_Size
$LockedBox.TabIndex = 0

$panel1.Controls.Add($LockedBox)


$UnlockAll.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 214
$System_Drawing_Point.Y = 120
$UnlockAll.Location = $System_Drawing_Point
$UnlockAll.Name = "UnlockAll"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 121
$UnlockAll.Size = $System_Drawing_Size
$UnlockAll.TabIndex = 3
$UnlockAll.Text = "Unlock All Acocunts"
$UnlockAll.UseVisualStyleBackColor = $True
$UnlockAll.add_Click($UnlockAll_OnClick)

$panel1.Controls.Add($UnlockAll)


$UnlockAccounts.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 214
$System_Drawing_Point.Y = 91
$UnlockAccounts.Location = $System_Drawing_Point
$UnlockAccounts.Name = "UnlockAccounts"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 121
$UnlockAccounts.Size = $System_Drawing_Size
$UnlockAccounts.TabIndex = 2
$UnlockAccounts.Text = "Unlock Account"
$UnlockAccounts.UseVisualStyleBackColor = $True
$UnlockAccounts.add_Click($UnlockAccounts_OnClick)

$panel1.Controls.Add($UnlockAccounts)



$tabPage2.BackColor = [System.Drawing.Color]::FromArgb(255,105,105,105)
$tabPage2.DataBindings.DefaultDataSourceUpdateMode = 0
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 4
$System_Drawing_Point.Y = 22
$tabPage2.Location = $System_Drawing_Point
$tabPage2.Name = "tabPage2"
$System_Windows_Forms_Padding = New-Object System.Windows.Forms.Padding
$System_Windows_Forms_Padding.All = 3
$System_Windows_Forms_Padding.Bottom = 3
$System_Windows_Forms_Padding.Left = 3
$System_Windows_Forms_Padding.Right = 3
$System_Windows_Forms_Padding.Top = 3
$tabPage2.Padding = $System_Windows_Forms_Padding
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 791
$System_Drawing_Size.Width = 1081
$tabPage2.Size = $System_Drawing_Size
$tabPage2.TabIndex = 1
$tabPage2.Text = "tabPage2"

$tabControl1.Controls.Add($tabPage2)
$panel2.BackColor = [System.Drawing.Color]::FromArgb(255,200,200,200)

$panel2.DataBindings.DefaultDataSourceUpdateMode = 0
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 8
$System_Drawing_Point.Y = 14
$panel2.Location = $System_Drawing_Point
$panel2.Name = "panel2"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 470
$System_Drawing_Size.Width = 605
$panel2.Size = $System_Drawing_Size
$panel2.TabIndex = 4

$tabPage2.Controls.Add($panel2)
$TPVersionLBL.BorderStyle = 2
$TPVersionLBL.DataBindings.DefaultDataSourceUpdateMode = 0
$TPVersionLBL.Font = New-Object System.Drawing.Font("Bookman Old Style",12,1,3,1)

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 19
$System_Drawing_Point.Y = 16
$TPVersionLBL.Location = $System_Drawing_Point
$TPVersionLBL.Name = "TPVersionLBL"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 555
$TPVersionLBL.Size = $System_Drawing_Size
$TPVersionLBL.TabIndex = 46
$TPVersionLBL.Text = "IAVM - SAS Third Party Version Config Updater"
$TPVersionLBL.TextAlign = 32

$panel2.Controls.Add($TPVersionLBL)

$label9.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 474
$System_Drawing_Point.Y = 325
$label9.Location = $System_Drawing_Point
$label9.Name = "label9"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 100
$label9.Size = $System_Drawing_Size
$label9.TabIndex = 45
$label9.Text = "label9"

$panel2.Controls.Add($label9)

$EMETlbl.BorderStyle = 2
$EMETlbl.DataBindings.DefaultDataSourceUpdateMode = 0
$EMETlbl.Font = New-Object System.Drawing.Font("Microsoft Sans Serif",8.25,1,3,1)

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 474
$System_Drawing_Point.Y = 205
$EMETlbl.Location = $System_Drawing_Point
$EMETlbl.Name = "EMETlbl"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 100
$EMETlbl.Size = $System_Drawing_Size
$EMETlbl.TabIndex = 44
$EMETlbl.Text = "EMET"
$EMETlbl.TextAlign = 32

$panel2.Controls.Add($EMETlbl)

$FLPGlbl.BorderStyle = 2
$FLPGlbl.DataBindings.DefaultDataSourceUpdateMode = 0
$FLPGlbl.Font = New-Object System.Drawing.Font("Microsoft Sans Serif",8.25,1,3,1)

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 474
$System_Drawing_Point.Y = 69
$FLPGlbl.Location = $System_Drawing_Point
$FLPGlbl.Name = "FLPGlbl"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 100
$FLPGlbl.Size = $System_Drawing_Size
$FLPGlbl.TabIndex = 43
$FLPGlbl.Text = "Flash Plugin"
$FLPGlbl.TextAlign = 32

$panel2.Controls.Add($FLPGlbl)

$label6.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 278
$System_Drawing_Point.Y = 325
$label6.Location = $System_Drawing_Point
$label6.Name = "label6"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 100
$label6.Size = $System_Drawing_Size
$label6.TabIndex = 42
$label6.Text = "label6"

$panel2.Controls.Add($label6)

$FFlbl.BorderStyle = 2
$FFlbl.DataBindings.DefaultDataSourceUpdateMode = 0
$FFlbl.Font = New-Object System.Drawing.Font("Microsoft Sans Serif",8.25,1,3,1)

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 278
$System_Drawing_Point.Y = 205
$FFlbl.Location = $System_Drawing_Point
$FFlbl.Name = "FFlbl"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 100
$FFlbl.Size = $System_Drawing_Size
$FFlbl.TabIndex = 41
$FFlbl.Text = "Mozilla Firefox"
$FFlbl.TextAlign = 32

$panel2.Controls.Add($FFlbl)

$FLAXlbl.BorderStyle = 2
$FLAXlbl.DataBindings.DefaultDataSourceUpdateMode = 0
$FLAXlbl.Font = New-Object System.Drawing.Font("Microsoft Sans Serif",8.25,1,3,1)

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 278
$System_Drawing_Point.Y = 69
$FLAXlbl.Location = $System_Drawing_Point
$FLAXlbl.Name = "FLAXlbl"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 100
$FLAXlbl.Size = $System_Drawing_Size
$FLAXlbl.TabIndex = 40
$FLAXlbl.Text = "Flash Active X"
$FLAXlbl.TextAlign = 32

$panel2.Controls.Add($FLAXlbl)

$JRElbl.BorderStyle = 2
$JRElbl.DataBindings.DefaultDataSourceUpdateMode = 0
$JRElbl.Font = New-Object System.Drawing.Font("Microsoft Sans Serif",8.25,1,3,1)

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 78
$System_Drawing_Point.Y = 325
$JRElbl.Location = $System_Drawing_Point
$JRElbl.Name = "JRElbl"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 100
$JRElbl.Size = $System_Drawing_Size
$JRElbl.TabIndex = 39
$JRElbl.Text = "Java Run Time"
$JRElbl.TextAlign = 32

$panel2.Controls.Add($JRElbl)

$SHlbl.BorderStyle = 2
$SHlbl.DataBindings.DefaultDataSourceUpdateMode = 0
$SHlbl.Font = New-Object System.Drawing.Font("Microsoft Sans Serif",8.25,1,3,1)

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 78
$System_Drawing_Point.Y = 205
$SHlbl.Location = $System_Drawing_Point
$SHlbl.Name = "SHlbl"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 100
$SHlbl.Size = $System_Drawing_Size
$SHlbl.TabIndex = 38
$SHlbl.Text = "Adobe Shockwave"
$SHlbl.TextAlign = 32

$panel2.Controls.Add($SHlbl)

$RDRlbl.BorderStyle = 2
$RDRlbl.DataBindings.DefaultDataSourceUpdateMode = 0
$RDRlbl.Font = New-Object System.Drawing.Font("Microsoft Sans Serif",8.25,1,3,1)

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 78
$System_Drawing_Point.Y = 69
$RDRlbl.Location = $System_Drawing_Point
$RDRlbl.Name = "RDRlbl"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 100
$RDRlbl.Size = $System_Drawing_Size
$RDRlbl.TabIndex = 37
$RDRlbl.Text = "Adobe Reader"
$RDRlbl.TextAlign = 32

$panel2.Controls.Add($RDRlbl)


$button21.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 499
$System_Drawing_Point.Y = 389
$button21.Location = $System_Drawing_Point
$button21.Name = "button21"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 75
$button21.Size = $System_Drawing_Size
$button21.TabIndex = 36
$button21.Text = "Update Now"
$button21.UseVisualStyleBackColor = $True
$button21.add_Click($button21_OnClick)

$panel2.Controls.Add($button21)


$EMETUpgr.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 499
$System_Drawing_Point.Y = 268
$EMETUpgr.Location = $System_Drawing_Point
$EMETUpgr.Name = "EMETUpgr"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 75
$EMETUpgr.Size = $System_Drawing_Size
$EMETUpgr.TabIndex = 35
$EMETUpgr.Text = "Update Now"
$EMETUpgr.UseVisualStyleBackColor = $True
$EMETUpgr.add_Click($EMETUpgr_OnClick)

$panel2.Controls.Add($EMETUpgr)


$FLPGUpgr.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 499
$System_Drawing_Point.Y = 135
$FLPGUpgr.Location = $System_Drawing_Point
$FLPGUpgr.Name = "FLPGUpgr"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 75
$FLPGUpgr.Size = $System_Drawing_Size
$FLPGUpgr.TabIndex = 34
$FLPGUpgr.Text = "Update Now"
$FLPGUpgr.UseVisualStyleBackColor = $True
$FLPGUpgr.add_Click($FLPGUpgr_OnClick)

$panel2.Controls.Add($FLPGUpgr)


$button18.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 417
$System_Drawing_Point.Y = 389
$button18.Location = $System_Drawing_Point
$button18.Name = "button18"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 75
$button18.Size = $System_Drawing_Size
$button18.TabIndex = 33
$button18.Text = "Current"
$button18.UseVisualStyleBackColor = $True
$button18.add_Click($button18_OnClick)

$panel2.Controls.Add($button18)


$EMETCurrent.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 417
$System_Drawing_Point.Y = 268
$EMETCurrent.Location = $System_Drawing_Point
$EMETCurrent.Name = "EMETCurrent"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 75
$EMETCurrent.Size = $System_Drawing_Size
$EMETCurrent.TabIndex = 32
$EMETCurrent.Text = "Current"
$EMETCurrent.UseVisualStyleBackColor = $True
$EMETCurrent.add_Click($EMETCurrent_OnClick)

$panel2.Controls.Add($EMETCurrent)


$FLPGCurrent.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 417
$System_Drawing_Point.Y = 136
$FLPGCurrent.Location = $System_Drawing_Point
$FLPGCurrent.Name = "FLPGCurrent"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 75
$FLPGCurrent.Size = $System_Drawing_Size
$FLPGCurrent.TabIndex = 31
$FLPGCurrent.Text = "Current"
$FLPGCurrent.UseVisualStyleBackColor = $True
$FLPGCurrent.add_Click($FLPGCurrent_OnClick)

$panel2.Controls.Add($FLPGCurrent)


$button15.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 301
$System_Drawing_Point.Y = 390
$button15.Location = $System_Drawing_Point
$button15.Name = "button15"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 75
$button15.Size = $System_Drawing_Size
$button15.TabIndex = 30
$button15.Text = "Update Now"
$button15.UseVisualStyleBackColor = $True
$button15.add_Click($button15_OnClick)

$panel2.Controls.Add($button15)


$FFUpgr.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 301
$System_Drawing_Point.Y = 269
$FFUpgr.Location = $System_Drawing_Point
$FFUpgr.Name = "FFUpgr"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 75
$FFUpgr.Size = $System_Drawing_Size
$FFUpgr.TabIndex = 29
$FFUpgr.Text = "Update Now"
$FFUpgr.UseVisualStyleBackColor = $True
$FFUpgr.add_Click($FFUpgr_OnClick)

$panel2.Controls.Add($FFUpgr)


$FLAXUpgr.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 301
$System_Drawing_Point.Y = 136
$FLAXUpgr.Location = $System_Drawing_Point
$FLAXUpgr.Name = "FLAXUpgr"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 75
$FLAXUpgr.Size = $System_Drawing_Size
$FLAXUpgr.TabIndex = 28
$FLAXUpgr.Text = "Update Now"
$FLAXUpgr.UseVisualStyleBackColor = $True
$FLAXUpgr.add_Click($FLAXUpgr_OnClick)

$panel2.Controls.Add($FLAXUpgr)


$button12.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 219
$System_Drawing_Point.Y = 390
$button12.Location = $System_Drawing_Point
$button12.Name = "button12"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 75
$button12.Size = $System_Drawing_Size
$button12.TabIndex = 27
$button12.Text = "Current"
$button12.UseVisualStyleBackColor = $True
$button12.add_Click($button12_OnClick)

$panel2.Controls.Add($button12)


$FFCurrent.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 219
$System_Drawing_Point.Y = 269
$FFCurrent.Location = $System_Drawing_Point
$FFCurrent.Name = "FFCurrent"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 75
$FFCurrent.Size = $System_Drawing_Size
$FFCurrent.TabIndex = 26
$FFCurrent.Text = "Current"
$FFCurrent.UseVisualStyleBackColor = $True
$FFCurrent.add_Click($FFCurrent_OnClick)

$panel2.Controls.Add($FFCurrent)


$FLAXCurrent.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 219
$System_Drawing_Point.Y = 137
$FLAXCurrent.Location = $System_Drawing_Point
$FLAXCurrent.Name = "FLAXCurrent"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 75
$FLAXCurrent.Size = $System_Drawing_Size
$FLAXCurrent.TabIndex = 25
$FLAXCurrent.Text = "Current"
$FLAXCurrent.UseVisualStyleBackColor = $True
$FLAXCurrent.add_Click($FLAXCurrent_OnClick)

$panel2.Controls.Add($FLAXCurrent)


$JREUpgr.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 100
$System_Drawing_Point.Y = 390
$JREUpgr.Location = $System_Drawing_Point
$JREUpgr.Name = "JREUpgr"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 75
$JREUpgr.Size = $System_Drawing_Size
$JREUpgr.TabIndex = 24
$JREUpgr.Text = "Update Now"
$JREUpgr.UseVisualStyleBackColor = $True
$JREUpgr.add_Click($JREUpgr_OnClick)

$panel2.Controls.Add($JREUpgr)


$SHUpgr.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 100
$System_Drawing_Point.Y = 269
$SHUpgr.Location = $System_Drawing_Point
$SHUpgr.Name = "SHUpgr"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 75
$SHUpgr.Size = $System_Drawing_Size
$SHUpgr.TabIndex = 23
$SHUpgr.Text = "Update Now"
$SHUpgr.UseVisualStyleBackColor = $True
$SHUpgr.add_Click($SHUpgr_OnClick)

$panel2.Controls.Add($SHUpgr)


$RDRUpgr.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 100
$System_Drawing_Point.Y = 136
$RDRUpgr.Location = $System_Drawing_Point
$RDRUpgr.Name = "RDRUpgr"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 75
$RDRUpgr.Size = $System_Drawing_Size
$RDRUpgr.TabIndex = 22
$RDRUpgr.Text = "Update Now"
$RDRUpgr.UseVisualStyleBackColor = $True
$RDRUpgr.add_Click($RDRUpgr_OnClick)

$panel2.Controls.Add($RDRUpgr)

$textBox9.BackColor = [System.Drawing.Color]::FromArgb(255,67,78,84)
$textBox9.DataBindings.DefaultDataSourceUpdateMode = 0
$textBox9.ForeColor = [System.Drawing.Color]::FromArgb(255,255,255,225)
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 417
$System_Drawing_Point.Y = 364
$textBox9.Location = $System_Drawing_Point
$textBox9.Name = "textBox9"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 20
$System_Drawing_Size.Width = 164
$textBox9.Size = $System_Drawing_Size
$textBox9.TabIndex = 21

$panel2.Controls.Add($textBox9)

$EMETtxt.BackColor = [System.Drawing.Color]::FromArgb(255,67,78,84)
$EMETtxt.DataBindings.DefaultDataSourceUpdateMode = 0
$EMETtxt.ForeColor = [System.Drawing.Color]::FromArgb(255,255,255,225)
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 417
$System_Drawing_Point.Y = 243
$EMETtxt.Location = $System_Drawing_Point
$EMETtxt.Name = "EMETtxt"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 20
$System_Drawing_Size.Width = 164
$EMETtxt.Size = $System_Drawing_Size
$EMETtxt.TabIndex = 20

$panel2.Controls.Add($EMETtxt)

$FLPGtxt.BackColor = [System.Drawing.Color]::FromArgb(255,67,78,84)
$FLPGtxt.DataBindings.DefaultDataSourceUpdateMode = 0
$FLPGtxt.ForeColor = [System.Drawing.Color]::FromArgb(255,255,255,225)
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 417
$System_Drawing_Point.Y = 110
$FLPGtxt.Location = $System_Drawing_Point
$FLPGtxt.Name = "FLPGtxt"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 20
$System_Drawing_Size.Width = 164
$FLPGtxt.Size = $System_Drawing_Size
$FLPGtxt.TabIndex = 19

$panel2.Controls.Add($FLPGtxt)

$textBox6.BackColor = [System.Drawing.Color]::FromArgb(255,67,78,84)
$textBox6.DataBindings.DefaultDataSourceUpdateMode = 0
$textBox6.ForeColor = [System.Drawing.Color]::FromArgb(255,255,255,225)
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 219
$System_Drawing_Point.Y = 364
$textBox6.Location = $System_Drawing_Point
$textBox6.Name = "textBox6"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 20
$System_Drawing_Size.Width = 164
$textBox6.Size = $System_Drawing_Size
$textBox6.TabIndex = 18

$panel2.Controls.Add($textBox6)

$FFtxt.BackColor = [System.Drawing.Color]::FromArgb(255,67,78,84)
$FFtxt.DataBindings.DefaultDataSourceUpdateMode = 0
$FFtxt.ForeColor = [System.Drawing.Color]::FromArgb(255,255,255,225)
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 219
$System_Drawing_Point.Y = 244
$FFtxt.Location = $System_Drawing_Point
$FFtxt.Name = "FFtxt"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 20
$System_Drawing_Size.Width = 164
$FFtxt.Size = $System_Drawing_Size
$FFtxt.TabIndex = 17

$panel2.Controls.Add($FFtxt)

$FLAXtxt.BackColor = [System.Drawing.Color]::FromArgb(255,67,78,84)
$FLAXtxt.DataBindings.DefaultDataSourceUpdateMode = 0
$FLAXtxt.ForeColor = [System.Drawing.Color]::FromArgb(255,255,255,225)
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 219
$System_Drawing_Point.Y = 110
$FLAXtxt.Location = $System_Drawing_Point
$FLAXtxt.Name = "FLAXtxt"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 20
$System_Drawing_Size.Width = 164
$FLAXtxt.Size = $System_Drawing_Size
$FLAXtxt.TabIndex = 16

$panel2.Controls.Add($FLAXtxt)


$pictureBox9.DataBindings.DefaultDataSourceUpdateMode = 0



$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 417
$System_Drawing_Point.Y = 309
$pictureBox9.Location = $System_Drawing_Point
$pictureBox9.Name = "pictureBox9"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 50
$System_Drawing_Size.Width = 52
$pictureBox9.Size = $System_Drawing_Size
$pictureBox9.TabIndex = 15
$pictureBox9.TabStop = $False

$panel2.Controls.Add($pictureBox9)

$pictureBox8.BackgroundImage = [System.Drawing.Image]::FromFile('<<Computer>>\Pictures\EMET.png')
$pictureBox8.BackgroundImageLayout = 3
$pictureBox8.DataBindings.DefaultDataSourceUpdateMode = 0



$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 417
$System_Drawing_Point.Y = 188
$pictureBox8.Location = $System_Drawing_Point
$pictureBox8.Name = "pictureBox8"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 50
$System_Drawing_Size.Width = 52
$pictureBox8.Size = $System_Drawing_Size
$pictureBox8.TabIndex = 14
$pictureBox8.TabStop = $False

$panel2.Controls.Add($pictureBox8)

$pictureBox7.BackgroundImage = [System.Drawing.Image]::FromFile('<<Computer>>\Pictures\Adobe-Flash-icon.jpg')
$pictureBox7.BackgroundImageLayout = 3
$pictureBox7.DataBindings.DefaultDataSourceUpdateMode = 0



$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 416
$System_Drawing_Point.Y = 54
$pictureBox7.Location = $System_Drawing_Point
$pictureBox7.Name = "pictureBox7"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 50
$System_Drawing_Size.Width = 52
$pictureBox7.Size = $System_Drawing_Size
$pictureBox7.TabIndex = 13
$pictureBox7.TabStop = $False

$panel2.Controls.Add($pictureBox7)


$pictureBox6.DataBindings.DefaultDataSourceUpdateMode = 0



$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 219
$System_Drawing_Point.Y = 309
$pictureBox6.Location = $System_Drawing_Point
$pictureBox6.Name = "pictureBox6"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 50
$System_Drawing_Size.Width = 52
$pictureBox6.Size = $System_Drawing_Size
$pictureBox6.TabIndex = 12
$pictureBox6.TabStop = $False

$panel2.Controls.Add($pictureBox6)

$pictureBox5.BackgroundImage = [System.Drawing.Image]::FromFile('<<Computer>>\Pictures\Firefiox-icon.jpg')
$pictureBox5.BackgroundImageLayout = 3
$pictureBox5.DataBindings.DefaultDataSourceUpdateMode = 0



$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 219
$System_Drawing_Point.Y = 188
$pictureBox5.Location = $System_Drawing_Point
$pictureBox5.Name = "pictureBox5"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 50
$System_Drawing_Size.Width = 52
$pictureBox5.Size = $System_Drawing_Size
$pictureBox5.TabIndex = 11
$pictureBox5.TabStop = $False

$panel2.Controls.Add($pictureBox5)

$pictureBox4.BackgroundImage = [System.Drawing.Image]::FromFile('<<Computer>>\Pictures\Adobe-Flash-icon.jpg')
$pictureBox4.BackgroundImageLayout = 3
$pictureBox4.DataBindings.DefaultDataSourceUpdateMode = 0



$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 219
$System_Drawing_Point.Y = 54
$pictureBox4.Location = $System_Drawing_Point
$pictureBox4.Name = "pictureBox4"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 50
$System_Drawing_Size.Width = 52
$pictureBox4.Size = $System_Drawing_Size
$pictureBox4.TabIndex = 10
$pictureBox4.TabStop = $False

$panel2.Controls.Add($pictureBox4)


$JRECurrent.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 19
$System_Drawing_Point.Y = 390
$JRECurrent.Location = $System_Drawing_Point
$JRECurrent.Name = "JRECurrent"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 75
$JRECurrent.Size = $System_Drawing_Size
$JRECurrent.TabIndex = 9
$JRECurrent.Text = "Current"
$JRECurrent.UseVisualStyleBackColor = $True
$JRECurrent.add_Click($JRECurrent_OnClick)

$panel2.Controls.Add($JRECurrent)


$SHCurrent.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 19
$System_Drawing_Point.Y = 269
$SHCurrent.Location = $System_Drawing_Point
$SHCurrent.Name = "SHCurrent"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 75
$SHCurrent.Size = $System_Drawing_Size
$SHCurrent.TabIndex = 8
$SHCurrent.Text = "Current"
$SHCurrent.UseVisualStyleBackColor = $True
$SHCurrent.add_Click($SHCurrent_OnClick)

$panel2.Controls.Add($SHCurrent)


$RDRCurrent.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 19
$System_Drawing_Point.Y = 137
$RDRCurrent.Location = $System_Drawing_Point
$RDRCurrent.Name = "RDRCurrent"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 75
$RDRCurrent.Size = $System_Drawing_Size
$RDRCurrent.TabIndex = 7
$RDRCurrent.Text = "Current"
$RDRCurrent.UseVisualStyleBackColor = $True
$RDRCurrent.add_Click($RDRCurrent_OnClick)

$panel2.Controls.Add($RDRCurrent)

$pictureBox3.BackgroundImage = [System.Drawing.Image]::FromFile('<<Computer>>\Pictures\java-icon.jpg')
$pictureBox3.BackgroundImageLayout = 3
$pictureBox3.DataBindings.DefaultDataSourceUpdateMode = 0



$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 19
$System_Drawing_Point.Y = 309
$pictureBox3.Location = $System_Drawing_Point
$pictureBox3.Name = "pictureBox3"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 50
$System_Drawing_Size.Width = 52
$pictureBox3.Size = $System_Drawing_Size
$pictureBox3.TabIndex = 6
$pictureBox3.TabStop = $False

$panel2.Controls.Add($pictureBox3)

$pictureBox2.BackgroundImage = [System.Drawing.Image]::FromFile('<<Computer>>\Pictures\Adobe-Shockwave-icon.jpg')
$pictureBox2.BackgroundImageLayout = 3
$pictureBox2.DataBindings.DefaultDataSourceUpdateMode = 0



$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 19
$System_Drawing_Point.Y = 188
$pictureBox2.Location = $System_Drawing_Point
$pictureBox2.Name = "pictureBox2"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 50
$System_Drawing_Size.Width = 52
$pictureBox2.Size = $System_Drawing_Size
$pictureBox2.TabIndex = 5
$pictureBox2.TabStop = $False

$panel2.Controls.Add($pictureBox2)

$pictureBox1.BackgroundImage = [System.Drawing.Image]::FromFile('<<Computer>>\Pictures\Adobe-Acrobat-Reader-icon.png')
$pictureBox1.BackgroundImageLayout = 3
$pictureBox1.DataBindings.DefaultDataSourceUpdateMode = 0



$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 19
$System_Drawing_Point.Y = 54
$pictureBox1.Location = $System_Drawing_Point
$pictureBox1.Name = "pictureBox1"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 50
$System_Drawing_Size.Width = 52
$pictureBox1.Size = $System_Drawing_Size
$pictureBox1.TabIndex = 4
$pictureBox1.TabStop = $False

$panel2.Controls.Add($pictureBox1)

$SHtxt.BackColor = [System.Drawing.Color]::FromArgb(255,67,78,84)
$SHtxt.DataBindings.DefaultDataSourceUpdateMode = 0
$SHtxt.ForeColor = [System.Drawing.Color]::FromArgb(255,255,255,225)
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 19
$System_Drawing_Point.Y = 244
$SHtxt.Location = $System_Drawing_Point
$SHtxt.Name = "SHtxt"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 20
$System_Drawing_Size.Width = 164
$SHtxt.Size = $System_Drawing_Size
$SHtxt.TabIndex = 2
$SHtxt.add_TextChanged($handler_textBox2_TextChanged)

$panel2.Controls.Add($SHtxt)

$JREtxt.BackColor = [System.Drawing.Color]::FromArgb(255,67,78,84)
$JREtxt.DataBindings.DefaultDataSourceUpdateMode = 0
$JREtxt.ForeColor = [System.Drawing.Color]::FromArgb(255,255,255,225)
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 19
$System_Drawing_Point.Y = 365
$JREtxt.Location = $System_Drawing_Point
$JREtxt.Name = "JREtxt"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 20
$System_Drawing_Size.Width = 164
$JREtxt.Size = $System_Drawing_Size
$JREtxt.TabIndex = 3
$JREtxt.add_TextChanged($handler_textBox3_TextChanged)

$panel2.Controls.Add($JREtxt)

$RDRtxt.BackColor = [System.Drawing.Color]::FromArgb(255,67,78,84)
$RDRtxt.DataBindings.DefaultDataSourceUpdateMode = 0
$RDRtxt.ForeColor = [System.Drawing.Color]::FromArgb(255,255,255,225)
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 19
$System_Drawing_Point.Y = 110
$RDRtxt.Location = $System_Drawing_Point
$RDRtxt.Name = "RDRtxt"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 20
$System_Drawing_Size.Width = 164
$RDRtxt.Size = $System_Drawing_Size
$RDRtxt.TabIndex = 1
$RDRtxt.add_TextChanged($handler_textBox1_TextChanged)

$panel2.Controls.Add($RDRtxt)




$toolBar1.DataBindings.DefaultDataSourceUpdateMode = 0
$toolBar1.DropDownArrows = $True
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 0
$System_Drawing_Point.Y = 0
$toolBar1.Location = $System_Drawing_Point
$toolBar1.Name = "toolBar1"
$toolBar1.ShowToolTips = $True
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 42
$System_Drawing_Size.Width = 1089
$toolBar1.Size = $System_Drawing_Size
$toolBar1.TabIndex = 0

$form1.Controls.Add($toolBar1)


#endregion Generated Form Code

#Save the initial state of the form
$InitialFormWindowState = $form1.WindowState
#Init the OnLoad event to correct the initial state of the form
$form1.add_Load($OnLoadForm_StateCorrection)
#Show the Form
$form1.ShowDialog()| Out-Null

} #End Function

#Call the Function
GenerateForm
